
Running tests... 
----------------------------------------------------------------------
 test_Login_with_valid_account (pages.components.main.Homepage_Test) ... FAIL (11.631119)s

======================================================================
FAIL [11.631119s]: pages.components.main.Homepage_Test.test_Login_with_valid_account
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Developer\Python Slenium\Hiko-Automation-Selenium\Template\src\pages\components\main.py", line 32, in test_Login_with_valid_account
    LOGIN.click(*HomePageLocators.btn_login)
  File "D:\Developer\Python Slenium\Hiko-Automation-Selenium\Template\src\pages\UIObject.py", line 165, in click
    self.get_element(wait)).click().perform()
  File "D:\Developer\Python Slenium\Hiko-Automation-Selenium\Template\src\pages\UIObject.py", line 33, in get_element
    self.wait_to_appear(wait)
  File "D:\Developer\Python Slenium\Hiko-Automation-Selenium\Template\src\pages\UIObject.py", line 98, in wait_to_appear
    raise AssertionError("Locator did not appear: {} in {} seconds!"
AssertionError: Locator did not appear: btn--home-login in btn--home-login seconds!
[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 89.0.4389
[WDM] - Get LATEST driver version for 89.0.4389
[WDM] - Driver [C:\Users\DELL\.wdm\drivers\chromedriver\win32\89.0.4389.23\chromedriver.exe] found in cache

----------------------------------------------------------------------
Ran 1 test in 0:00:11

FAILED
 (Failures=1)

Generating HTML reports... 
reports\TestResults_pages.components.main.Homepage_Test_2021-03-15_17-10-35.html
